#!/usr/bin/env bash

# Used for converting one to many xpt files
# Usage example: 
#   xpt2csv filename.xpt
#   xpt2csv *.xpt

for arg; do
    file_name=$(echo "$arg" | cut -d '.' -f 1)
    python -m xport "${file_name}.XPT" > "${file_name}.csv" && rm "${file_name}.XPT"
done
